version: '2.2'

services:

  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-data:/var/log/rabbitmq
    networks:
      - rabbitmq-network

volumes:
  rabbitmq-data:
    driver: local

networks:
  rabbitmq-network:
    driver: bridge